name: C/C++ CI

on:
  push:
    paths:
      - '**.c'
    paths-ignore:
      - 'docs/**'      
    branches: [ main, develop]
  pull_request:
    branches: [ main, develop ]
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
