name: C/C++ CI

on:
  push:
    paths:
      - '**.c'
    paths-ignore:
      - 'docs/**'      
    branches: [ main, develop]
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron '30 5,17 * * *'  
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: compile
      run: gcc main.c -o main
    - name: run
      run: ./main